export const MENU_ACCESS_ITEMS = [
  { key: 'home', group: 'General', label: 'Home' },

  { key: 'products.dashboard', group: 'Products', label: 'Dashboard' },
  { key: 'products.list', group: 'Products', label: 'List Products' },
  { key: 'products.add', group: 'Products', label: 'Add Product' },
  { key: 'products.updatePrice', group: 'Products', label: 'Update Price' },
  { key: 'products.importProducts', group: 'Products', label: 'Import Products' },
  { key: 'products.importOpeningStock', group: 'Products', label: 'Import Opening Stock' },
  { key: 'products.categories', group: 'Products', label: 'Categories' },
  { key: 'products.brands', group: 'Products', label: 'Brands' },
  { key: 'products.warranties', group: 'Products', label: 'Warranties' },
  { key: 'products.stockAdjustment', group: 'Products', label: 'Stock Adjustment' },
  { key: 'orders.list', group: 'Products', label: 'Orders List' },
  { key: 'brands.list', group: 'Products', label: 'Brands List' },
  { key: 'promotions.list', group: 'Products', label: 'Promotions' },
  { key: 'promotions.create', group: 'Products', label: 'Create Promotion' },

  { key: 'users.list', group: 'User Management', label: 'Users List' },
  { key: 'users.roles', group: 'User Management', label: 'Roles' },
  { key: 'users.permissions', group: 'User Management', label: 'Permissions' },

  { key: 'contacts.customers', group: 'Contacts', label: 'Customers' },
  { key: 'contacts.vendors', group: 'Contacts', label: 'Vendors' },

  { key: 'purchases.requisition', group: 'Purchases', label: 'Purchase Requisition' },
  { key: 'purchases.order', group: 'Purchases', label: 'Purchase Order' },
  { key: 'purchases.list', group: 'Purchases', label: 'List Purchases' },
  { key: 'purchases.add', group: 'Purchases', label: 'Add Purchase' },
  { key: 'purchases.returns', group: 'Purchases', label: 'List Purchase Return' },

  { key: 'bi.dashboard', group: 'Business Intelligence', label: 'BI Dashboard' },
  { key: 'bi.insights', group: 'Business Intelligence', label: 'AI Insights' },
  { key: 'bi.analytics', group: 'Business Intelligence', label: 'Analytics' },

  { key: 'sell.salesOrder', group: 'Sell', label: 'Sales Order' },
  { key: 'sell.allSales', group: 'Sell', label: 'All Sales' },
  { key: 'sell.posList', group: 'Sell', label: 'List POS' },
  { key: 'sell.pos', group: 'Sell', label: 'POS' },
  { key: 'sell.quotationsAdd', group: 'Sell', label: 'Add Quotation' },
  { key: 'sell.quotationsList', group: 'Sell', label: 'List Quotations' },
  { key: 'sell.returns', group: 'Sell', label: 'List Sell Return' },
  { key: 'sell.shipments', group: 'Sell', label: 'Shipments' },
  { key: 'sell.discounts', group: 'Sell', label: 'Discounts' },

  { key: 'expenses', group: 'Expenses', label: 'Expenses' },

  { key: 'paymentAccounts.accounts', group: 'Payment Accounts', label: 'Accounts' },
  { key: 'paymentAccounts.balanceSheet', group: 'Payment Accounts', label: 'Balance Sheet' },
  { key: 'paymentAccounts.trialBalance', group: 'Payment Accounts', label: 'Trial Balance' },
  { key: 'paymentAccounts.cashFlow', group: 'Payment Accounts', label: 'Cash Flow' },

  { key: 'accounting.dashboard', group: 'Accounting', label: 'Accounting Dashboard' },
  { key: 'accounting.chartOfAccounts', group: 'Accounting', label: 'Chart of Accounts' },
  { key: 'accounting.journalEntries', group: 'Accounting', label: 'Journal Entries' },
  { key: 'accounting.transactions', group: 'Accounting', label: 'Transactions' },
  { key: 'accounting.reports', group: 'Accounting', label: 'Reports' },
  { key: 'accounting.financialReports', group: 'Accounting', label: 'Financial Reports' },
  { key: 'accounting.vendors', group: 'Accounting', label: 'Vendors' },

  { key: 'reports.profitLoss', group: 'Reports', label: 'Profit / Loss Report' },
  { key: 'reports.purchaseSale', group: 'Reports', label: 'Purchase & Sale' },
  { key: 'reports.tax', group: 'Reports', label: 'Tax Report' },
  { key: 'reports.supplierCustomer', group: 'Reports', label: 'Supplier & Customer Report' },
  { key: 'reports.customerGroups', group: 'Reports', label: 'Customer Groups Report' },
  { key: 'reports.stock', group: 'Reports', label: 'Stock Report' },
  { key: 'reports.stockExpiry', group: 'Reports', label: 'Stock Expiry Report' },
  { key: 'reports.lot', group: 'Reports', label: 'Lot Report' },
  { key: 'reports.stockAdjustment', group: 'Reports', label: 'Stock Adjustment Report' },
  { key: 'reports.trendingProducts', group: 'Reports', label: 'Trending Products' },
  { key: 'reports.items', group: 'Reports', label: 'Items Report' },
  { key: 'reports.productPurchase', group: 'Reports', label: 'Product Purchase Report' },
  { key: 'reports.productSell', group: 'Reports', label: 'Product Sell Report' },
  { key: 'reports.purchasePayment', group: 'Reports', label: 'Purchase Payment Report' },
  { key: 'reports.sellPayment', group: 'Reports', label: 'Sell Payment Report' },
  { key: 'reports.expense', group: 'Reports', label: 'Expense Report' },
  { key: 'reports.register', group: 'Reports', label: 'Register Report' },
  { key: 'reports.salesRepresentative', group: 'Reports', label: 'Sales Representative Report' },
  { key: 'reports.activityLog', group: 'Reports', label: 'Activity Log' },

  { key: 'settings', group: 'General', label: 'Settings' },
  { key: 'woocommerce', group: 'General', label: 'WooCommerce' }
]
