CREATE TABLE IF NOT EXISTS "Order" (
    id TEXT PRIMARY KEY,
    "wooId" INTEGER UNIQUE NOT NULL,
    "orderNumber" TEXT UNIQUE NOT NULL,
    "customerId" INTEGER,
    status TEXT NOT NULL,
    total TEXT,
    subtotal TEXT,
    "shippingTotal" TEXT,
    "taxTotal" TEXT,
    "discountTotal" TEXT,
    "paymentMethod" TEXT,
    "paymentMethodTitle" TEXT,
    "customerNote" TEXT,
    "dateCreated" TIMESTAMPTZ,
    "datePaid" TIMESTAMPTZ,
    "dateCompleted" TIMESTAMPTZ,
    "shippingAddress" TEXT DEFAULT '{}',
    "billingAddress" TEXT DEFAULT '{}',
    "lineItems" TEXT DEFAULT '[]',
    customer TEXT DEFAULT '{}',
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,
    "syncedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
